TrailORG/src/objects/Address__c.object
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrailORG/src/objects/Company__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Owner_Name__c</fullName>
        <label>Company Owner Name</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrailORG/src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>Employees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee_Designation__c</fullName>
        <label>Employee Designation</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrailORG/src/classes/WizardController.cls
public class WizardController
        {
        
        public Company__c comp{get; set;}
       public Employee__c emp{get; set;}
       // public static String mid;
        public WizardController(){
        
        
        comp=new Company__c();
        emp=new Employee__c();
        
        }
        public PageReference save()
        {if(comp==null)
        {
        comp=new Company__c();
        }
        if(comp.Name==''||comp.Address__c==''||comp.Company_Owner_Name__c==''||comp.Country__c==''||comp.State__c==''||comp.Zip_Code__c=='')
        {ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Please enter value'));
        
            return null;
        }
       insert comp;
        PageReference compPage = new PageReference('https://ap2.salesforce.com/'+ comp.id);
        compPage.setRedirect(true);
        return compPage;
        }
        
        
        
        
        
        
        
        
        public PageReference CreateEmployee()
        {
        if(comp==null)
        {
        comp=new Company__c();
        }
        if(comp.Name==''||comp.Address__c==''||comp.Company_Owner_Name__c==''||comp.Country__c==''||comp.State__c==''||comp.Zip_Code__c=='')
        {ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Please enter value'));
        
            return null;
        }
       insert comp;
       System.debug('id>>>>>'+comp.id);
      // wizardController.mid=comp.id;
        PageReference compPage = new PageReference('https://c.ap2.visual.force.com/apex/EmployeePage');
        compPage.getParameters().put('id',comp.Id);

        compPage.setRedirect(true);
        return compPage;
        }
        
        
        
        
        
            public PageReference save1()
            {if(emp==null)
            {
            emp=new Employee__c();
            }
            Company__c c=[select id from Company__c where id=:comp.Id limit 2];
            emp.Company__c=c.id;
            if(emp.Name==''||emp.Email__c==''||emp.Phone__c==''||emp.Employee_Designation__c=='')
            {ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Please enter value'));
            
                return null;
            }
           emp.Company__c=ApexPages.currentPage().getParameters().get('Id');
           insert emp;
            PageReference empPage = new PageReference('https://ap2.salesforce.com/'+ emp.id);
            empPage.setRedirect(true);
            return empPage;
            }
            
            
            
            
            
             public PageReference savenew()
            {if(emp==null)
            {
            emp=new Employee__c();
            }
            if(emp.Name==''||emp.Email__c==''||emp.Phone__c==''||emp.Employee_Designation__c=='')
            {ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Please enter value'));
            
                return null;
            }
            
            emp.Company__c=ApexPages.currentPage().getParameters().get('Id');
           
            //System.debug('mid>>>>>>>>>'+WizardController.mid);
           insert emp;
            PageReference empPage = new PageReference('https://c.ap2.visual.force.com/apex/EmployeePage');
            empPage.setRedirect(true);
            return empPage;
            }
            
            
        }